### ISSUE TITLE
bower.json main attribute

### ISSUE THREAD

**Issue by tylerthebuildor** [dnomak/flexiblegs-scss-plus#18]
I used bower to add flexiblegs to my project and I use gulp to inject my deps. I got this error:
`flexible.gs was not injected in your file. Please go take a look in "src/bower_components/flexible.gs" for the file you need, then manually include it in your file.`

I fixed the problem by pointing to the css file in the flexiblegs .bower.json file with this line:
`"main": "static/css/flexiblegs/flexiblegs.css"`

I would of just made a pull request but I don't see a .bower.json file in the current Github repo and am a little confused how that all works. I've never published to bower. Also I realize this might be intentional because there are Sass, LESS, and Stylus options. A workaround would be nice though. It's annoying when bower components don't just work after install.

**Comment by dnomak** [comment]
thank you :) http://bower.io/search/?q=flexiblegs

**Comment by tylerthebuildor** [comment]
No problem thanks for the sweet lib :D

**Comment by dnomak** [comment]
thank you so much :D
