### ISSUE TITLE
Comparison with flexboxgrid

### ISSUE THREAD

**Issue by dandv** [dnomak/flexiblegs-scss-plus#20]
Interesting library! 

I see it was started in June 2014, when http://flexboxgrid.com/ already existed, so I'm curious what were the reasons for creating a different library, and how it compares with @kristoferjoseph's [Flexboxgrid](https://github.com/kristoferjoseph/flexboxgrid/).

Thanks

**Comment by dnomak** [comment]
my english is not good sorry :( flexbox is just a css feature. please check out @dandv @kristoferjoseph.
- http://flexible.gs/learning/flexbox/?framework=css
  - http://flexible.gs/learning/middle/?framework=css
  - http://flexible.gs/learning/bottom/?framework=css
  - http://flexible.gs/learning/between/?framework=css
  - http://flexible.gs/learning/around/?framework=css
  - http://flexible.gs/learning/baseline/?framework=css
  - http://flexible.gs/learning/first/?framework=css
  - http://flexible.gs/learning/last/?framework=css
  - http://flexible.gs/learning/reverse/?framework=css

**Comment by dnomak** [comment]
the most important feature http://flexible.gs/learning/col-width/?framework=css @dandv
