### ISSUE TITLE
kod tekrarı düzeltilmeli

### ISSUE THREAD

**Issue by dnomak** [dnomak/flexiblegs-scss-plus#28]
18 ve 369 satırın içindeki each'ler tekrar ediyor bu durumun düzeltilmesi gerekiyor.

https://github.com/flexiblegs/flexiblegs-scss/blob/master/flexiblegs-scss.scss#L18
https://github.com/flexiblegs/flexiblegs-scss/blob/master/flexiblegs-scss.scss#L369

**Comment by dnomak** [comment]
@burakcan bu issue'yu kapatmama yardımcı olabilirmisin?

**Comment by burakcan** [comment]
@dnomak bakiyorum

**Comment by dnomak** [comment]
tamamdır

**Comment by dnomak** [comment]
yaptığım bir update sonrası satırlar güncellendi.

https://github.com/flexiblegs/flexiblegs-scss/blob/master/flexiblegs-scss.scss#L18
https://github.com/flexiblegs/flexiblegs-scss/blob/master/flexiblegs-scss.scss#L369

**Comment by dnomak** [comment]
@bcinarli @ademilter destek istiyorum :) bu durumu düzeltmemizin bir yolu var mı ?

**Comment by bcinarli** [comment]
Ben niye forklayamıyorum bu repoyu?

**Comment by dnomak** [comment]
organizasyonda olup repoda tanımlı olmadığın için olabilir diye düşünüp repo'ya ekledim seni tekrar bakarmısın.

**Comment by bcinarli** [comment]
İlk etapda mixin (çok quick-win) üzerinden en azından kodların tekrar yazılmasını giderdim ama item each olayını düzeltebiliriz gibi geliyor. Bir de dependency ayarları ile gulp tasklarını ekledim. Sen geliştirmeyi nasıl yapıyorsun :)
Refactoring branchı üzerinde çalıştım hızlıca, oturup bakarız beraber içeriklerine
https://github.com/flexiblegs/flexiblegs-scss/blob/refactoring/flexiblegs-scss.scss

**Comment by dnomak** [comment]
sassmeister veya codepen üzerinden amelelikle yapıyorum geliştirmeyi :) çalıştığım proje üzerinde bower ile ekliyorum gulp task'leri hallediyor işi onuda yeomanle oluşturmuştum senin repo için gulp taski eklemen süper oldu fırsat bulup bakamamıştım bir türlü :)

**Comment by burakcan** [comment]
ovv :( unutmusum ben bunu abi :(

**Comment by dnomak** [comment]
tahmin ettim abi senide sıkıştırmamak için böyle bir hatırlatma yapıyım dedim :) bu arada yeni birşeyler daha yaptım adem abi'ye ilettim linki sizde fırsat bulduğunuzda bir inceleyin lütfen https://github.com/flexiblegs/flexiblecss-scss

@f abi sende incele lütfen birde ben burağa kendi kendime kızmıştım ya biz konuştuk barıştık :)
burak sana kızıp fatihe şikayet etmiştim seni konuyu biliyosun :D

**Comment by bcinarli** [comment]
Bu arada dependencyler ve tanımlar ile alakalı olarak, normal beklenti, senin uyguladığının tam tersi şeklinde oluyor. Şimdilik durumda, flexiblegs-scss, flexiblegs-scss-plus'a dependent olmuş. Bunun tersi daha doğru olacak. Plus olanın base'e bağımlı olması lazım, base'in plus'a değil :)

Bir de csslint ekledim, özel ayar yapmadan, 564 tane uyarı veriyor. Onları bir gözden geçirelim. Prefixler için, postcss ya da autoprefixer tarzı bir kurgu daha iyi olabilir.

**Comment by dnomak** [comment]
anladım abi tamamdır.

**Comment by bcinarli** [comment]
Bir de eski sitede demolar vardı, şimdi yok :/ o yüzden revize edilen kodun akışı bozup bozmadığını test etmek zorlaşıyor

**Comment by dnomak** [comment]
abi süper faydalı geri bildirimlerin için çok teşekkür ederim bir sürü iş çıkarttın bana inanılmaz mutlu oldum :)

**Comment by bcinarli** [comment]
görmediysen,

> ilk başlangıçta, bütün elemanları `*` ile `inline-block` yapıyor, sonra tabloyu fln orjinal haline getiriyorsun
> 
> bcinarli [1:31 PM]
> oradaki kurguyu düzeltirsek, sonrasında bu eachler içindeki yapıyı sadeleştirmek daha rahat olucak
> 
> bcinarli [1:36 PM]
> şuanda 4600 satır oluyor çıktı, bunu 2bin satıra fln kolayca düşürürüz gibi geldi

**Comment by dnomak** [comment]
settings.scss kısmında css veya bem olmalı aslında 2'sinden biri seçildiğinde 2bin satıra iniyor ama farklı bir durumdan mı bahsettin acaba yukarıda tam anlayamadım aslında.

**Comment by dnomak** [comment]
hmm aslında şimdi anladım 2'sinin aynı anda kullanılması durumunda içlerindeki css özellikleri tek kalabilir bu durumda çok iyi olur tabi.

**Comment by dnomak** [comment]
@bcinarli merge işlemi tamamdır :) diğer detaylar için başka issue oluşturacağım.
